// This file will be auto-generated by Supabase CLI
// For now, we'll define a basic structure that matches our schema

export type Json =
  | string
  | number
  | boolean
  | null
  | { [key: string]: Json | undefined }
  | Json[]

export interface Database {
  public: {
    Tables: {
      user_profiles: {
        Row: {
          id: string
          name: string
          avatar: string
          created_at: string
          updated_at: string
        }
        Insert: {
          id: string
          name: string
          avatar: string
          created_at?: string
          updated_at?: string
        }
        Update: {
          id?: string
          name?: string
          avatar?: string
          created_at?: string
          updated_at?: string
        }
      }
      events: {
        Row: {
          id: string
          host_id: string
          title: string
          description: string
          activity_type: string
          location: string
          coordinates: Json
          start_time: string
          end_time: string | null
          is_flexible_start: boolean
          is_flexible_end: boolean
          privacy: 'OPEN' | 'INVITE_ONLY'
          target_group: 'ALL_FRIENDS' | 'CLIMBERS' | 'FAMILY' | 'WORK'
          max_seats: number | null
          no_phones: boolean
          created_at: string
          updated_at: string
        }
        Insert: {
          id?: string
          host_id: string
          title: string
          description: string
          activity_type: string
          location: string
          coordinates: Json
          start_time: string
          end_time?: string | null
          is_flexible_start?: boolean
          is_flexible_end?: boolean
          privacy?: 'OPEN' | 'INVITE_ONLY'
          target_group?: 'ALL_FRIENDS' | 'CLIMBERS' | 'FAMILY' | 'WORK'
          max_seats?: number | null
          no_phones?: boolean
          created_at?: string
          updated_at?: string
        }
        Update: {
          id?: string
          host_id?: string
          title?: string
          description?: string
          activity_type?: string
          location?: string
          coordinates?: Json
          start_time?: string
          end_time?: string | null
          is_flexible_start?: boolean
          is_flexible_end?: boolean
          privacy?: 'OPEN' | 'INVITE_ONLY'
          target_group?: 'ALL_FRIENDS' | 'CLIMBERS' | 'FAMILY' | 'WORK'
          max_seats?: number | null
          no_phones?: boolean
          created_at?: string
          updated_at?: string
        }
      }
      event_attendees: {
        Row: {
          id: string
          event_id: string
          user_id: string
          joined_at: string
        }
        Insert: {
          id?: string
          event_id: string
          user_id: string
          joined_at?: string
        }
        Update: {
          id?: string
          event_id?: string
          user_id?: string
          joined_at?: string
        }
      }
      comments: {
        Row: {
          id: string
          event_id: string
          user_id: string
          text: string
          timestamp: string
          created_at: string
        }
        Insert: {
          id?: string
          event_id: string
          user_id: string
          text: string
          timestamp?: string
          created_at?: string
        }
        Update: {
          id?: string
          event_id?: string
          user_id?: string
          text?: string
          timestamp?: string
          created_at?: string
        }
      }
      reactions: {
        Row: {
          id: string
          event_id: string
          user_id: string
          emoji: string
          created_at: string
        }
        Insert: {
          id?: string
          event_id: string
          user_id: string
          emoji: string
          created_at?: string
        }
        Update: {
          id?: string
          event_id?: string
          user_id?: string
          emoji?: string
          created_at?: string
        }
      }
      notifications: {
        Row: {
          id: string
          user_id: string
          type: 'INVITE' | 'COMMENT' | 'REACTION' | 'REMINDER' | 'SYSTEM'
          title: string
          message: string
          timestamp: string
          related_event_id: string | null
          is_read: boolean
          actor_id: string | null
          created_at: string
        }
        Insert: {
          id?: string
          user_id: string
          type: 'INVITE' | 'COMMENT' | 'REACTION' | 'REMINDER' | 'SYSTEM'
          title: string
          message: string
          timestamp?: string
          related_event_id?: string | null
          is_read?: boolean
          actor_id?: string | null
          created_at?: string
        }
        Update: {
          id?: string
          user_id?: string
          type?: 'INVITE' | 'COMMENT' | 'REACTION' | 'REMINDER' | 'SYSTEM'
          title?: string
          message?: string
          timestamp?: string
          related_event_id?: string | null
          is_read?: boolean
          actor_id?: string | null
          created_at?: string
        }
      }
      user_friends: {
        Row: {
          id: string
          user_id: string
          friend_id: string
          created_at: string
        }
        Insert: {
          id?: string
          user_id: string
          friend_id: string
          created_at?: string
        }
        Update: {
          id?: string
          user_id?: string
          friend_id?: string
          created_at?: string
        }
      }
      user_groups: {
        Row: {
          id: string
          user_id: string
          group_type: 'ALL_FRIENDS' | 'CLIMBERS' | 'FAMILY' | 'WORK'
          created_at: string
        }
        Insert: {
          id?: string
          user_id: string
          group_type: 'ALL_FRIENDS' | 'CLIMBERS' | 'FAMILY' | 'WORK'
          created_at?: string
        }
        Update: {
          id?: string
          user_id?: string
          group_type?: 'ALL_FRIENDS' | 'CLIMBERS' | 'FAMILY' | 'WORK'
          created_at?: string
        }
      }
    }
    Views: {
      [_ in never]: never
    }
    Functions: {
      [_ in never]: never
    }
    Enums: {
      event_privacy: 'OPEN' | 'INVITE_ONLY'
      event_group: 'ALL_FRIENDS' | 'CLIMBERS' | 'FAMILY' | 'WORK'
      notification_type: 'INVITE' | 'COMMENT' | 'REACTION' | 'REMINDER' | 'SYSTEM'
    }
  }
}

