// This file will be auto-generated by Supabase CLI
// For now, we'll define a basic structure that matches our schema

export type Json =
  | string
  | number
  | boolean
  | null
  | { [key: string]: Json | undefined }
  | Json[]

export interface Database {
  public: {
    Tables: {
      user_profiles: {
        Row: {
          id: string
          name: string
          avatar: string
          is_admin: boolean
          created_at: string
          updated_at: string
        }
        Insert: {
          id: string
          name: string
          avatar: string
          is_admin?: boolean
          created_at?: string
          updated_at?: string
        }
        Update: {
          id?: string
          name?: string
          avatar?: string
          is_admin?: boolean
          created_at?: string
          updated_at?: string
        }
      }
      events: {
        Row: {
          id: string
          host_id: string
          slug: string
          title: string
          description: string
          activity_type: string
          header_image_url: string | null
          header_image_position_y: number | null
          location: string
          coordinates: Json | null
          location_data: Json | null
          start_time: string
          end_time: string | null
          is_flexible_start: boolean
          is_flexible_end: boolean
          visibility_type: 'ALL_FRIENDS' | 'GROUPS' | 'INVITE_ONLY'
          allow_friend_invites: boolean
          max_seats: number | null
          no_phones: boolean
          itinerary_time_display: 'START_ONLY' | 'START_AND_END'
          created_at: string
          updated_at: string
        }
        Insert: {
          id?: string
          host_id: string
          slug?: string
          title: string
          description: string
          activity_type: string
          header_image_url?: string | null
          header_image_position_y?: number | null
          location: string
          coordinates?: Json | null
          location_data?: Json | null
          start_time: string
          end_time?: string | null
          is_flexible_start?: boolean
          is_flexible_end?: boolean
          visibility_type?: 'ALL_FRIENDS' | 'GROUPS' | 'INVITE_ONLY'
          allow_friend_invites?: boolean
          max_seats?: number | null
          no_phones?: boolean
          itinerary_time_display?: 'START_ONLY' | 'START_AND_END'
          created_at?: string
          updated_at?: string
        }
        Update: {
          id?: string
          host_id?: string
          slug?: string
          title?: string
          description?: string
          activity_type?: string
          header_image_url?: string | null
          header_image_position_y?: number | null
          location?: string
          coordinates?: Json | null
          location_data?: Json | null
          start_time?: string
          end_time?: string | null
          is_flexible_start?: boolean
          is_flexible_end?: boolean
          visibility_type?: 'ALL_FRIENDS' | 'GROUPS' | 'INVITE_ONLY'
          allow_friend_invites?: boolean
          max_seats?: number | null
          no_phones?: boolean
          itinerary_time_display?: 'START_ONLY' | 'START_AND_END'
          created_at?: string
          updated_at?: string
        }
      }
      event_attendees: {
        Row: {
          id: string
          event_id: string
          user_id: string
          joined_at: string
        }
        Insert: {
          id?: string
          event_id: string
          user_id: string
          joined_at?: string
        }
        Update: {
          id?: string
          event_id?: string
          user_id?: string
          joined_at?: string
        }
      }
      comments: {
        Row: {
          id: string
          event_id: string
          user_id: string
          text: string
          timestamp: string
          created_at: string
        }
        Insert: {
          id?: string
          event_id: string
          user_id: string
          text: string
          timestamp?: string
          created_at?: string
        }
        Update: {
          id?: string
          event_id?: string
          user_id?: string
          text?: string
          timestamp?: string
          created_at?: string
        }
      }
      reactions: {
        Row: {
          id: string
          event_id: string
          user_id: string
          emoji: string
          created_at: string
        }
        Insert: {
          id?: string
          event_id: string
          user_id: string
          emoji: string
          created_at?: string
        }
        Update: {
          id?: string
          event_id?: string
          user_id?: string
          emoji?: string
          created_at?: string
        }
      }
      notifications: {
        Row: {
          id: string
          user_id: string
          type: 'INVITE' | 'COMMENT' | 'REACTION' | 'REMINDER' | 'SYSTEM'
          title: string
          message: string
          timestamp: string
          related_event_id: string | null
          is_read: boolean
          actor_id: string | null
          created_at: string
        }
        Insert: {
          id?: string
          user_id: string
          type: 'INVITE' | 'COMMENT' | 'REACTION' | 'REMINDER' | 'SYSTEM'
          title: string
          message: string
          timestamp?: string
          related_event_id?: string | null
          is_read?: boolean
          actor_id?: string | null
          created_at?: string
        }
        Update: {
          id?: string
          user_id?: string
          type?: 'INVITE' | 'COMMENT' | 'REACTION' | 'REMINDER' | 'SYSTEM'
          title?: string
          message?: string
          timestamp?: string
          related_event_id?: string | null
          is_read?: boolean
          actor_id?: string | null
          created_at?: string
        }
      }
      user_friends: {
        Row: {
          id: string
          user_id: string
          friend_id: string
          created_at: string
        }
        Insert: {
          id?: string
          user_id: string
          friend_id: string
          created_at?: string
        }
        Update: {
          id?: string
          user_id?: string
          friend_id?: string
          created_at?: string
        }
      }
      groups: {
        Row: {
          id: string
          name: string
          created_by: string
          updated_by: string | null
          is_open: boolean
          deleted_at: string | null
          created_at: string
          updated_at: string
        }
        Insert: {
          id?: string
          name: string
          created_by: string
          updated_by?: string | null
          is_open?: boolean
          deleted_at?: string | null
          created_at?: string
          updated_at?: string
        }
        Update: {
          id?: string
          name?: string
          created_by?: string
          updated_by?: string | null
          is_open?: boolean
          deleted_at?: string | null
          created_at?: string
          updated_at?: string
        }
      }
      user_groups: {
        Row: {
          id: string
          user_id: string
          group_id: string
          role: 'MEMBER' | 'ADMIN'
          joined_at: string
          created_at: string
        }
        Insert: {
          id?: string
          user_id: string
          group_id: string
          role?: 'MEMBER' | 'ADMIN'
          joined_at?: string
          created_at?: string
        }
        Update: {
          id?: string
          user_id?: string
          group_id?: string
          role?: 'MEMBER' | 'ADMIN'
          joined_at?: string
          created_at?: string
        }
      }
      event_groups: {
        Row: {
          id: string
          event_id: string
          group_id: string
          created_at: string
        }
        Insert: {
          id?: string
          event_id: string
          group_id: string
          created_at?: string
        }
        Update: {
          id?: string
          event_id?: string
          group_id?: string
          created_at?: string
        }
      }
      event_invites: {
        Row: {
          id: string
          event_id: string
          user_id: string
          invited_by: string | null
          invited_at: string
          created_at: string
        }
        Insert: {
          id?: string
          event_id: string
          user_id: string
          invited_by?: string | null
          invited_at?: string
          created_at?: string
        }
        Update: {
          id?: string
          event_id?: string
          user_id?: string
          invited_by?: string | null
          invited_at?: string
          created_at?: string
        }
      }
      event_itinerary_items: {
        Row: {
          id: string
          event_id: string
          title: string
          start_time: string
          duration_minutes: number
          location: string | null
          description: string | null
          created_at: string
          updated_at: string
        }
        Insert: {
          id?: string
          event_id: string
          title: string
          start_time: string
          duration_minutes: number
          location?: string | null
          description?: string | null
          created_at?: string
          updated_at?: string
        }
        Update: {
          id?: string
          event_id?: string
          title?: string
          start_time?: string
          duration_minutes?: number
          location?: string | null
          description?: string | null
          created_at?: string
          updated_at?: string
        }
      }
      event_expenses: {
        Row: {
          id: string
          event_id: string
          title: string
          applies_to: string
          split_type: string
          timing: string
          settled_kind: string | null
          amount_cents: number | null
          currency: string
          participant_ids: string[]
          sort_order: number
          created_at: string
          updated_at: string
        }
        Insert: {
          id?: string
          event_id: string
          title: string
          applies_to?: string
          split_type: string
          timing: string
          settled_kind?: string | null
          amount_cents?: number | null
          currency?: string
          participant_ids: string[]
          sort_order?: number
          created_at?: string
          updated_at?: string
        }
        Update: {
          id?: string
          event_id?: string
          title?: string
          applies_to?: string
          split_type?: string
          timing?: string
          settled_kind?: string | null
          amount_cents?: number | null
          currency?: string
          participant_ids?: string[]
          sort_order?: number
          created_at?: string
          updated_at?: string
        }
      }
      user_feedback: {
        Row: {
          id: string
          user_id: string
          title: string
          type: 'bug' | 'feature' | 'ux' | 'other'
          importance: 'low' | 'medium' | 'high' | 'critical'
          description: string
          status: 'new' | 'reviewed' | 'planned' | 'done' | 'declined'
          created_at: string
          updated_at: string
        }
        Insert: {
          id?: string
          user_id: string
          title: string
          type: 'bug' | 'feature' | 'ux' | 'other'
          importance: 'low' | 'medium' | 'high' | 'critical'
          description: string
          status?: 'new' | 'reviewed' | 'planned' | 'done' | 'declined'
          created_at?: string
          updated_at?: string
        }
        Update: {
          id?: string
          user_id?: string
          title?: string
          type?: 'bug' | 'feature' | 'ux' | 'other'
          importance?: 'low' | 'medium' | 'high' | 'critical'
          description?: string
          status?: 'new' | 'reviewed' | 'planned' | 'done' | 'declined'
          created_at?: string
          updated_at?: string
        }
      }
      feedback_projects: {
        Row: {
          id: string
          title: string
          description: string | null
          status: 'backlog' | 'on_deck' | 'in_progress' | 'review' | 'completed' | 'archived'
          sort_order: number
          github_repo: string | null
          github_url: string | null
          created_at: string
          updated_at: string
        }
        Insert: {
          id?: string
          title: string
          description?: string | null
          status?: 'backlog' | 'on_deck' | 'in_progress' | 'review' | 'completed' | 'archived'
          sort_order?: number
          github_repo?: string | null
          github_url?: string | null
          created_at?: string
          updated_at?: string
        }
        Update: {
          id?: string
          title?: string
          description?: string | null
          status?: 'backlog' | 'on_deck' | 'in_progress' | 'review' | 'completed' | 'archived'
          sort_order?: number
          github_repo?: string | null
          github_url?: string | null
          created_at?: string
          updated_at?: string
        }
      }
      feedback_project_items: {
        Row: {
          id: string
          project_id: string
          feedback_id: string
          created_at: string
        }
        Insert: {
          id?: string
          project_id: string
          feedback_id: string
          created_at?: string
        }
        Update: {
          id?: string
          project_id?: string
          feedback_id?: string
          created_at?: string
        }
      }
    }
    Views: {
      [_ in never]: never
    }
    Functions: {
      [_ in never]: never
    }
    Enums: {
      event_visibility_type: 'ALL_FRIENDS' | 'GROUPS' | 'INVITE_ONLY'
      notification_type: 'INVITE' | 'COMMENT' | 'REACTION' | 'REMINDER' | 'SYSTEM'
      feedback_type: 'bug' | 'feature' | 'ux' | 'other'
      feedback_importance: 'low' | 'medium' | 'high' | 'critical'
      feedback_status: 'new' | 'reviewed' | 'planned' | 'done' | 'declined'
      feedback_project_status: 'backlog' | 'on_deck' | 'in_progress' | 'review' | 'completed' | 'archived'
    }
  }
}
